services:

  tempo:
    image: grafana/tempo:2.7.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-config/tempo-local.yml:/etc/tempo.yaml
      - ./tempo-config/tempo-data:/var/tempo
    ports:
#      - "14268:14268"  # Jaeger ingest
      - "3200:3200"   # Tempo Interface
#      - "6831:6831/udp" # jaeger UDP
      - "4318:4318" # OpenTelemetry HTTP
    networks:
      - monitoramento
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090 # HTTP
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    networks:
      - monitoramento
  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./grafana-provisining:/etc/grafana/provisioning/datasources
    ports:
     - '8080:3000'
    networks:
    - monitoramento
networks:
  monitoramento:
    name: monitoramento
    external: true
